"use client"

// The Reference shelf: every guide as its own cover, filed by subject.
//
// These are standalone documents (public/reference/*.html) that each want the
// whole window — they carry their own audio, metronomes and canvases. They
// used to sit behind accordion rows that embedded them in tall iframes, which
// meant the shelf told you nothing about a guide until you opened it, and
// opening one gave you a document squeezed into a scrolling box inside
// another scrolling page. Now the shelf shows what each guide actually looks
// like (covers in public/reference/thumbs/, regenerated by
// scripts/make-reference-thumbs.mjs) and clicking one opens it in its own tab,
// full size, the way it was built to be read.
//
// Exported so PickupPracticeHome's "Core curriculum" row can link to the same
// guides instead of keeping its own separate list — it reads title, subtitle
// and src, so those three keep their names.
export const GUIDES = [
  {
    title: "Pentatonic 3:2 Navigator",
    subtitle: "Diagonal fretboard-freedom shapes, moved through real changes — standalone, with its own audio and metronome",
    src: "/reference/pentatonic-32-navigator.html",
    thumb: "/reference/thumbs/pentatonic-32-navigator.jpg",
    category: "improv",
    color: "var(--db-c-blue)",
  },
  {
    title: "Barry Harris Practice Regimen & Pivots",
    subtitle: "Interactive guitar reference",
    src: "/reference/likas-page-2-guitar.html",
    thumb: "/reference/thumbs/likas-page-2-guitar.jpg",
    category: "improv",
    color: "var(--db-c-gold)",
  },
  {
    title: "Triad Network",
    subtitle: "Interactive practice system and tutorial",
    src: "/reference/triad-network.html",
    thumb: "/reference/thumbs/triad-network.jpg",
    category: "improv",
    color: "var(--db-c-purple)",
  },
  {
    title: "Blues Pathways",
    subtitle: "B♭ jazz blues fretboard scale explorer — pentatonic, bebop, Martino conversion and altered scales per chord",
    src: "/reference/blues-pathways.html",
    thumb: "/reference/thumbs/blues-pathways.jpg",
    category: "improv",
    color: "var(--db-c-amber)",
  },
  {
    title: "Open Tunings 1",
    subtitle: "Seven open tunings — chord charts, capo hacks, and songs",
    src: "/reference/open-tunings-1.html",
    thumb: "/reference/thumbs/open-tunings-1.jpg",
    category: "tunings",
    color: "var(--db-c-blue)",
  },
  {
    title: "Open Tunings 2",
    subtitle: "A working guitarist's field guide to seven open tunings",
    src: "/reference/open-tunings-2.html",
    thumb: "/reference/thumbs/open-tunings-2.jpg",
    category: "tunings",
    color: "var(--db-c-green)",
  },
  {
    title: "Tavern Set",
    subtitle: "Editable lead sheets",
    src: "/reference/tavern-set.html",
    thumb: "/reference/thumbs/tavern-set.jpg",
    category: "leadsheets",
    color: "var(--db-c-amber)",
  },
  {
    title: "The Martin 000",
    subtitle: "History, construction, players, songs & buying guide",
    src: "/reference/martin-000-buying-guide.html",
    thumb: "/reference/thumbs/martin-000-buying-guide.jpg",
    category: "equipment",
    color: "var(--db-c-salmon)",
  },
  {
    title: "Mesa Boogie",
    subtitle: "Mesa/Boogie & F-30 deep dive — history, tubes, controls, presets",
    src: "/reference/mesaboogie.html",
    thumb: "/reference/thumbs/mesaboogie.jpg",
    category: "equipment",
    color: "var(--db-c-blue)",
  },
]

// Subject order is the reading order of the shelf, not the order the guides
// happen to sit in GUIDES (that one is the Practice home's curriculum
// sequence, which follows the learning path instead).
const SECTIONS = [
  { id: "improv",     label: "Improv",      blurb: "Systems for making lines" },
  { id: "tunings",    label: "Tunings",     blurb: "Off standard, and what to play there" },
  { id: "equipment",  label: "Equipment",   blurb: "Guitars and amps, in depth" },
  { id: "leadsheets", label: "Lead Sheets", blurb: "Tunes, ready to play" },
]

export default function ReferenceGuides() {
  return (
    <div style={{ marginBottom: "20px" }}>
      <style>{`
        .db-ref-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
          gap: 14px;
        }
        .db-ref-card {
          display: flex; flex-direction: column;
          border: 1px solid var(--db-panel-border);
          border-radius: var(--db-r-md);
          background: var(--db-panel-bg);
          overflow: hidden;
          text-decoration: none;
          color: inherit;
          transition: transform .14s ease, box-shadow .14s ease, border-color .14s ease;
        }
        .db-ref-card:hover, .db-ref-card:focus-visible {
          transform: translateY(-2px);
          border-color: var(--db-accent);
          box-shadow: 0 6px 20px color-mix(in srgb, var(--db-text) 14%, transparent);
        }
        .db-ref-card:focus-visible { outline: 2px solid var(--db-accent); outline-offset: 2px; }
        /* The cover is the document's own first screen, shot at desktop
           width — cropped to a consistent 4:3 so a shelf of guides lines up
           however tall each page happens to be. */
        .db-ref-cover {
          position: relative;
          aspect-ratio: 4 / 3;
          background: var(--surface2);
          border-bottom: 1px solid var(--db-panel-border);
          overflow: hidden;
        }
        .db-ref-cover img {
          width: 100%; height: 100%;
          object-fit: cover; object-position: top center;
          display: block;
        }
        .db-ref-open {
          position: absolute; top: 8px; right: 8px;
          font: 700 9.5px 'IBM Plex Mono', monospace;
          letter-spacing: .1em; text-transform: uppercase;
          padding: 3px 7px; border-radius: 999px;
          background: color-mix(in srgb, var(--db-bg) 82%, transparent);
          border: 1px solid var(--db-panel-border);
          color: var(--db-muted);
          opacity: 0; transition: opacity .14s ease;
        }
        .db-ref-card:hover .db-ref-open,
        .db-ref-card:focus-visible .db-ref-open { opacity: 1; }
        @media (hover: none) { .db-ref-open { opacity: 1; } }
        .db-ref-meta { padding: 9px 11px 11px; display: flex; flex-direction: column; gap: 3px; }
        @media (prefers-reduced-motion: reduce) {
          .db-ref-card { transition: none; }
          .db-ref-card:hover, .db-ref-card:focus-visible { transform: none; }
        }
      `}</style>

      {SECTIONS.map((section) => {
        const items = GUIDES.filter((g) => g.category === section.id)
        if (!items.length) return null
        return (
          <section key={section.id} style={{ marginBottom: "26px" }}>
            <div style={{
              display: "flex", alignItems: "baseline", gap: "10px",
              flexWrap: "wrap", marginBottom: "10px",
            }}>
              <h3 style={{
                margin: 0, font: "800 13px 'IBM Plex Mono', monospace",
                letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--db-text)",
              }}>
                {section.label}
              </h3>
              <span style={{ fontSize: "var(--db-fs-sm)", color: "var(--db-muted)" }}>
                {section.blurb}
              </span>
              <span aria-hidden="true" style={{
                flex: 1, minWidth: "20px", height: "1px",
                background: "var(--db-panel-border)", alignSelf: "center",
              }} />
            </div>

            <div className="db-ref-grid">
              {items.map((guide) => (
                <a
                  key={guide.src}
                  className="db-ref-card"
                  href={guide.src}
                  target="_blank"
                  rel="noopener noreferrer"
                  title={`${guide.title} — opens in a new tab`}
                >
                  <div className="db-ref-cover">
                    {/* Decorative: the title right below it already names the
                        guide, so alt would only repeat it to a screen reader. */}
                    <img src={guide.thumb} alt="" loading="lazy" />
                    <span className="db-ref-open">Open ↗</span>
                  </div>
                  <div className="db-ref-meta">
                    <span style={{
                      font: "800 13.5px 'Instrument Sans', sans-serif",
                      color: guide.color, letterSpacing: "0.01em", lineHeight: 1.25,
                    }}>
                      {guide.title}
                    </span>
                    <span style={{
                      fontSize: "var(--db-fs-xs)", color: "var(--db-muted)", lineHeight: 1.4,
                    }}>
                      {guide.subtitle}
                    </span>
                  </div>
                </a>
              ))}
            </div>
          </section>
        )
      })}
    </div>
  )
}
